[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
log_level = info
log_handler = :INFO
admin_passwd = admin_dev_change_me
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_maxconn = 64
proxy_mode = False
workers = 0
max_cron_threads = 1
limit_time_cpu = 600
limit_time_real = 1200
